jupyter extension - create config parent directory if it doesn't exist (#9676)
if the config file's parent directory does not exist, an exception will
be thrown:
```
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/home/jovyan/extension-wd/jupyterlab_pachyderm/handlers.py", line 369, in put
        write_config(self.client.address, self.client.root_certs, None)
      File "/home/jovyan/extension-wd/jupyterlab_pachyderm/handlers.py", line 573, in write_config
        config.write(PACH_CONFIG)
      File "/opt/conda/lib/python3.9/site-packages/pachyderm_sdk/config.py", line 139, in write
        with config_file.open("w") as file_out:
      File "/opt/conda/lib/python3.9/pathlib.py", line 1252, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/opt/conda/lib/python3.9/pathlib.py", line 1120, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.pachyderm/config.json'
```
this change updates the extension to create the parent directory if it
does not already exist.
[INT-1173](https://pachyderm.atlassian.net/browse/INT-1173)

[INT-1173]:
https://pachyderm.atlassian.net/browse/INT-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Co-authored-by: Kevin Yang <kevin.yang@hpe.com>